#!/usr/bin/env node
'use strict';
/**
 * Regenerates generated/ from contracts/:
 *   generated/json-schema/bundle.json   every schema keyed by contract id (for registries and docs)
 *   generated/typescript/index.d.ts     types for every contract
 * `--check` fails if the committed output is stale (used by CI).
 */
const fs = require('fs');
const path = require('path');
const { compile } = require('json-schema-to-typescript');

const ROOT = path.join(__dirname, '..');
const catalog = JSON.parse(fs.readFileSync(path.join(ROOT, 'contracts/catalog.json'), 'utf8')).contracts;
const CHECK = process.argv.includes('--check');

(async () => {
    const bundle = { _about: 'Generated by scripts/generate.js. Do not edit.', contracts: {} };
    let dts = '/* Generated by scripts/generate.js from contracts/. Do not edit. */\n/* eslint-disable */\n';
    for (const entry of catalog) {
        const file = path.join(ROOT, 'contracts', entry.schema);
        const schema = JSON.parse(fs.readFileSync(file, 'utf8'));
        bundle.contracts[entry.id] = { version: entry.version, owner: entry.owner, status: entry.status, schema };
        const ts = await compile(schema, schema.title, {
            bannerComment: '', cwd: path.dirname(file), declareExternallyReferenced: false,
            additionalProperties: false, strictIndexSignatures: true, format: true,
            $refOptions: { resolve: { http: false } },
        });
        dts += `\n/** ${entry.id}@${entry.version} (owner: ${entry.owner}) */\n${ts}`;
    }
    const out = {
        'generated/json-schema/bundle.json': JSON.stringify(bundle, null, 2) + '\n',
        'generated/typescript/index.d.ts': dts,
    };
    let stale = [];
    for (const [rel, body] of Object.entries(out)) {
        const p = path.join(ROOT, rel);
        const prev = fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : null;
        if (prev !== body) {
            if (CHECK) stale.push(rel); else { fs.mkdirSync(path.dirname(p), { recursive: true }); fs.writeFileSync(p, body); }
        }
    }
    if (stale.length) { console.error(`stale generated files (run npm run generate): ${stale.join(', ')}`); process.exit(1); }
    console.log(CHECK ? 'generated/: up to date' : 'generated/: written');
})().catch(e => { console.error(e); process.exit(1); });
